# Generated by Django 4.1 on 2022-08-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_asesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('cantidad', models.IntegerField(default=0, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('No iniciado', 'No iniciado'), ('Medio camino', 'Iniciado'), ('Completado', 'Completado')], max_length=200, null=True)),
            ],
        ),
    ]
