# Generated by Django 4.1 on 2022-08-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_logro_asesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logro',
            name='asesor',
        ),
        migrations.AddField(
            model_name='logro',
            name='asesor',
            field=models.ManyToManyField(to='users.asesor'),
        ),
    ]
