# Generated by Django 4.0.3 on 2022-08-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_logro_asesor_logro_asesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logro',
            name='asesor',
        ),
        migrations.AddField(
            model_name='logro',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.asesor'),
        ),
        migrations.AlterField(
            model_name='logro',
            name='status',
            field=models.CharField(choices=[('No iniciado', 'No iniciado'), ('Iniciado', 'Iniciado'), ('Completado', 'Completado')], max_length=200, null=True),
        ),
    ]
